spring.application.name=demo


info.app.name=My swag app
logging.level.com.spring.demo.rest=debug
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

spring.datasource.url=jdbc:postgresql://localhost:5432
spring.datasource.username=username
spring.datasource.password=password